const mongoose = require("mongoose");

const TrainingSchema = new mongoose.Schema({
  available_as_one_time_purchase: { type: Boolean, default: false },
  available_in_subscription: { type: Boolean, default: false },
  avg_training_review: { type: Number, default: 0 },
  benefits: { type: String },
  content_type: { type: String },
  created_at: { type: Date },
  current_user_bookmark: { type: Number, default: 0 },
  current_user_like: { type: Number, default: 0 },
  current_user_total_lesson: { type: Number, default: 0 },
  description: { type: String },
  disable_comment: { type: Boolean, default: false },
  discount_percentage: { type: Number, default: null },
  duration: { type: String },
  es_exported: { type: Boolean, default: false },
  expiry_date: { type: Date, default: null },
  file_duration: { type: String, default: null },
  file_upload_without_prefix: { type: String },
  following: { type: Boolean, default: false },
  is_current_user_enrolled: { type: Boolean, default: false },
  is_current_user_purchased: { type: Boolean, default: false },
  is_free: { type: Boolean, default: false },
  is_harmfull: { type: Boolean, default: false },
  is_imported: { type: Boolean, default: false },
  is_optin_free: { type: Boolean, default: false },
  is_paid: { type: Boolean, default: false },
  is_share_on: { type: Boolean, default: true },
  preview: { type: String, default: null },
  price: { type: String },
  pricing_method: { type: String, default: null },
  progress_notifications: { type: Boolean, default: false },
  progress_tracking: { type: Boolean, default: false },
  status: { type: String },
  title: { type: String },
  training_slug: { type: String },
  turn_off_commenting: { type: Boolean, default: false },
  type: { type: String },
  updated_at: { type: Date },
  imageUpload: {
    type: String,
    default: null,
  },
  created_at: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model("Training", TrainingSchema);
